### PR TITLE
Setup rails api

### PR DESCRIPTION
**Pull request by akarmes**
## Status

**READY**
## Migrations

You have to setup database and change config/database.yml
## Description
- created `.ruby-version` and `.ruby-gemset`
- run `rails-api new . -T -d postgresql`
- added and initialized `rails-rspec`
## Steps to Test

```
$ git pull
$ git checkout setup-rails-api
$ bundle

setup database and change config/database.yml

$ rails s
```

### CODE REVIEW

**Comment by akarmes** [comment]
There's some issue with gem "spring": for some reason it takes almost 60s to load `rails s`. Any ideas why? `rails c` is ok, like 1-2s.

**Comment by isisAnchalee** [comment]
I created a pull-request template that we can use before merging :)

**Comment by akarmes** [comment]
@isisAnchalee pull request template? Is it some new GH feature? I've never heard about it.

**Comment by isisAnchalee** [comment]
https://github.com/ilooklike/ilooklike.us/wiki/Pull-Request-Template
Hehe oops my bad for not explaining.

Just a markdown template we can use when creating PRs for organization/documentation to make collaborating easier to follow.

**Comment by akarmes** [comment]
Maybe I should remove `config/database.yml` from repo, then add it `.gitignore` and create template file `config/database.yml.example`. What do you think?

**Comment by isisAnchalee** [comment]
I agree we should beef up the .gitignore.

```
/.idea/*
/tmp/*
/log/*
vendor/bundle/*
.bundle*
tmp/**/*
/coverage/*

# Local configuration
config/database.yml
config/session_keys.yml
log/development.log
```

**Comment by akarmes** [comment]
there's mistake in your example: `/log/*` covers `log/development.log`

**Comment by isisAnchalee** [comment]
whoops ^ good catch.

**Comment by akarmes** [comment]
Also I think that `/.idea/*` should not go to project `.gitignore`. Otherwise you will have to add project files for every IDE or text editor. It's better to use global ~/.gitignore for that.

**Pull request closed without merging**
